-- =====================================================================
--  QuizMania - sample data (generated; run AFTER schema.sql)
--
--  Demo accounts
--    Admin        admin@quiz.com        / admin123
--    Quiz Creator creator@quiz.com      / creator123   (also creator2@quiz.com)
--    Participant  participant@quiz.com  / participant123
--    (diya@, rohan@, sneha@, kabir@quiz.com use participant123 too)
-- =====================================================================
USE online_quiz;

INSERT INTO users(id,name,email,password_hash,role,active,created_at) VALUES
(1,'System Admin','admin@quiz.com','pbkdf2$65536$mwa7L6A/wwO3UU4brwP+5w==$Xv6c72w13fU3KLY7x3E9oUz/sfRFHYFtuPMw70naknw=','ADMIN',1,NOW() - INTERVAL 24 DAY),
(2,'Mr. Sharma','creator@quiz.com','pbkdf2$65536$nyImJnAW6oFn/surWjv/5g==$hCfSDybDP4bmY+jFRY05GFSEIOCvClvr/7u/DIucizE=','CREATOR',1,NOW() - INTERVAL 23 DAY),
(3,'Ms. Verma','creator2@quiz.com','pbkdf2$65536$IlPWr07RpDfu7ChcImr50w==$AY3jx6Cwl3ERRi5Bvg4lI0asFF6FdaxFOdhXTZh2TD8=','CREATOR',1,NOW() - INTERVAL 22 DAY),
(4,'Aarav Mehta','participant@quiz.com','pbkdf2$65536$UILbpXlYiYnYge0mX53NLQ==$GJfPA5h5CpsoreKJ7ofO9lFLjeAhp8t25NND9tfmfnI=','PARTICIPANT',1,NOW() - INTERVAL 21 DAY),
(5,'Diya Nair','diya@quiz.com','pbkdf2$65536$R/ruy0pNA3kazKFCyDokPA==$rmtPCQi3jBnH1f32WQD7XSBh+y1w/pQKjJCtl/m+GcY=','PARTICIPANT',1,NOW() - INTERVAL 20 DAY),
(6,'Rohan Gupta','rohan@quiz.com','pbkdf2$65536$yqpy9339PlP4hbn0hQFQVg==$SCzvzKK7hQM2oFYm79OUpuVPOvDw73Ck/r7bh2plp7g=','PARTICIPANT',1,NOW() - INTERVAL 19 DAY),
(7,'Sneha Iyer','sneha@quiz.com','pbkdf2$65536$XF4DyBiaD6R2Z6cAnZascA==$RJ02aI5RPAL5hFjK628aZ39PfricBGZzzgTeS7IaChY=','PARTICIPANT',1,NOW() - INTERVAL 18 DAY),
(8,'Kabir Singh','kabir@quiz.com','pbkdf2$65536$Pit72avCWMjj6NCUQsOqtA==$iBSZo3obrgxY0ZFVrsK2hs7N37E6CjYkHqQ0XrAfUc0=','PARTICIPANT',1,NOW() - INTERVAL 17 DAY);

INSERT INTO quizzes(id,title,description,duration_minutes,creator_id,status,review_note,created_at) VALUES
(1,'Java Fundamentals','Core syntax, primitive types and the building blocks of every Java program.',10,2,'APPROVED',NULL,NOW() - INTERVAL 22 DAY),
(2,'Object-Oriented Programming in Java','Inheritance, polymorphism, abstraction and encapsulation.',12,2,'APPROVED',NULL,NOW() - INTERVAL 20 DAY),
(3,'Collections & Generics','Lists, sets, maps and type-safe generic code.',12,3,'APPROVED',NULL,NOW() - INTERVAL 18 DAY),
(4,'Exceptions & Multithreading','Handle errors gracefully and run code concurrently.',15,3,'APPROVED',NULL,NOW() - INTERVAL 16 DAY),
(5,'JDBC & Servlets Basics','Talk to a database and handle web requests.',10,2,'PENDING',NULL,NOW() - INTERVAL 3 DAY),
(6,'Java 17 Features','Records, text blocks and switch expressions.',8,3,'DRAFT',NULL,NOW() - INTERVAL 3 DAY),
(7,'Strings & Arrays','Working with text and fixed-size collections.',8,2,'REJECTED','Questions 2 and 3 are too easy and there are no explanations. Add explanations and a harder question, then re-submit.',NOW() - INTERVAL 5 DAY);

INSERT INTO questions(id,quiz_id,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES
(1,1,'Which keyword is used to create a subclass in Java?','implements','extends','inherits','super','B','`extends` creates class inheritance. `implements` is used for interfaces.'),
(2,1,'How many bits does an int occupy in Java?','8','16','32','64','C','An int is always 32 bits, regardless of the platform.'),
(3,1,'Which of these is NOT a primitive type?','boolean','char','String','double','C','String is a class (reference type), not a primitive.'),
(4,1,'What is the entry point of a standalone Java application?','public void main(String[] args)','public static void main(String[] args)','static main()','void start()','B','The JVM looks for public static void main(String[] args).'),
(5,1,'What is the default value of a boolean instance variable?','true','false','null','0','B','Instance booleans default to false.'),
(6,1,'Which keyword prevents a variable from being reassigned?','static','final','const','volatile','B','`final` variables can be assigned only once. `const` is reserved but unused.'),
(7,2,'Method overriding is an example of which OOP concept?','Encapsulation','Runtime polymorphism','Compile-time polymorphism','Abstraction','B','The method that runs is chosen at runtime based on the object type.'),
(8,2,'Can an interface have a constructor?','Yes','No','Only if it is abstract','Only static ones','B','Interfaces cannot be instantiated and therefore have no constructors.'),
(9,2,'Which access modifier makes a member visible only inside its own class?','public','protected','default (package-private)','private','D','`private` limits access to the declaring class.'),
(10,2,'What does super() do inside a constructor?','Calls the parent class constructor','Creates a new object','Calls the overridden method','Ends the constructor','A','It invokes the superclass constructor and must be the first statement.'),
(11,2,'How many classes can a Java class directly extend?','One','Two','Unlimited','None','A','Java supports single inheritance of classes (but many interfaces).'),
(12,2,'Which statement about abstract classes is true?','They can be instantiated','They can contain abstract and concrete methods','They cannot have fields','They must be final','B','An abstract class may mix abstract and implemented methods and have fields.'),
(13,3,'Which collection does NOT allow duplicate elements?','ArrayList','LinkedList','HashSet','Vector','C','A Set stores unique elements.'),
(14,3,'Which Map implementation keeps its keys sorted?','HashMap','LinkedHashMap','TreeMap','Hashtable','C','TreeMap orders keys using natural ordering or a Comparator.'),
(15,3,'What is the average time complexity of HashMap.get()?','O(n)','O(1)','O(log n)','O(n log n)','B','Hashing gives constant time on average.'),
(16,3,'What does List<? extends Number> accept?','Only Number','Number or any of its subclasses','Any object','Only Integer','B','The upper-bounded wildcard allows Number and its subtypes (for reading).'),
(17,3,'Which interface defines the natural ordering of a class?','Comparator','Comparable','Iterable','Cloneable','B','Comparable.compareTo defines the natural order.'),
(18,3,'Which choice is best for a FIFO queue?','Stack','ArrayDeque used as a Queue','TreeSet','HashMap','B','ArrayDeque is the recommended general purpose queue.'),
(19,4,'Which of these is a checked exception?','NullPointerException','IOException','ArithmeticException','IllegalArgumentException','B','IOException must be caught or declared; the others are unchecked.'),
(20,4,'Which block runs whether or not an exception occurs?','try','catch','finally','throw','C','`finally` always executes (barring System.exit or a crash).'),
(21,4,'Which method actually starts a new thread?','run()','start()','begin()','execute()','B','start() creates the thread and calls run() on it. Calling run() directly does not.'),
(22,4,'What does the synchronized keyword guarantee?','Faster execution','Only one thread at a time can run the block for the same lock','Threads run in order','No exceptions are thrown','B','It provides mutual exclusion on the monitor of the lock object.'),
(23,4,'Which interface represents a task that returns a result?','Runnable','Callable','Thread','Executor','B','Callable<V>.call() returns a value and may throw checked exceptions.'),
(24,4,'A try-with-resources resource must implement:','Serializable','AutoCloseable','Cloneable','Runnable','B','The resource is closed automatically via AutoCloseable.close().'),
(25,5,'Which interface should be used to run parameterised SQL safely?','Statement','PreparedStatement','ResultSet','Driver','B','PreparedStatement prevents SQL injection by binding parameters.'),
(26,5,'Which method moves a ResultSet to the next row?','next()','move()','forward()','step()','A','next() returns false when there are no more rows.'),
(27,5,'Which HTTP method suits a form that changes data?','GET','POST','HEAD','TRACE','B','POST is for requests that change state.'),
(28,5,'Which object represents a user session in a servlet?','HttpSession','ServletConfig','ServletContext','RequestDispatcher','A','HttpSession keeps per-user state between requests.'),
(29,5,'Which servlet method is called once when the servlet is created?','service()','init()','destroy()','doGet()','B','The container calls init() once before any request.'),
(30,5,'What does response.sendRedirect() do?','Forwards on the server','Tells the browser to make a new request','Includes another page','Closes the session','B','It sends a 302 so the browser requests the new URL.'),
(31,6,'Which feature provides concise immutable data carriers?','record','enum','interface','abstract class','A','A record generates constructor, accessors, equals, hashCode and toString.'),
(32,6,'Which delimiter starts a text block?','"""','''''''','```','###','A','Text blocks start and end with three double quotes.'),
(33,6,'Which symbol is used in a switch expression case?','->','=>',':=','::','A','Switch expressions use the arrow form `case X -> value`.'),
(34,7,'Strings in Java are:','Mutable','Immutable','Volatile','Transient','B',NULL),
(35,7,'Which class is mutable and thread-safe for building strings?','StringBuilder','StringBuffer','String','CharSequence','B',NULL),
(36,7,'What is the index of the last element of an array of length n?','n','n-1','n+1','0','B',NULL);

INSERT INTO quiz_attempts(id,quiz_id,participant_id,score,auto_score,total_questions,started_at,submitted_at,feedback,graded_by,graded_at) VALUES
(1,1,4,3,3,6,(NOW() - INTERVAL 13 DAY - INTERVAL 10 HOUR - INTERVAL 3 MINUTE),(NOW() - INTERVAL 13 DAY - INTERVAL 10 HOUR),'Good understanding of the basics. Practice generics wildcards a bit more.',2,(NOW() - INTERVAL 13 DAY - INTERVAL 10 HOUR)),
(2,1,4,5,5,6,(NOW() - INTERVAL 12 DAY - INTERVAL 16 HOUR - INTERVAL 4 MINUTE),(NOW() - INTERVAL 12 DAY - INTERVAL 16 HOUR),NULL,NULL,NULL),
(3,2,4,4,4,6,(NOW() - INTERVAL 3 DAY - INTERVAL 10 HOUR - INTERVAL 8 MINUTE),(NOW() - INTERVAL 3 DAY - INTERVAL 10 HOUR),NULL,NULL,NULL),
(4,1,5,5,5,6,(NOW() - INTERVAL 12 DAY - INTERVAL 19 HOUR - INTERVAL 5 MINUTE),(NOW() - INTERVAL 12 DAY - INTERVAL 19 HOUR),'Excellent result - keep it up!',2,(NOW() - INTERVAL 12 DAY - INTERVAL 19 HOUR)),
(5,2,5,5,5,6,(NOW() - INTERVAL 8 DAY - INTERVAL 10 HOUR - INTERVAL 7 MINUTE),(NOW() - INTERVAL 8 DAY - INTERVAL 10 HOUR),NULL,NULL,NULL),
(6,3,5,6,6,6,(NOW() - INTERVAL 7 DAY - INTERVAL 12 HOUR - INTERVAL 8 MINUTE),(NOW() - INTERVAL 7 DAY - INTERVAL 12 HOUR),NULL,NULL,NULL),
(7,4,5,6,6,6,(NOW() - INTERVAL 4 DAY - INTERVAL 11 HOUR - INTERVAL 6 MINUTE),(NOW() - INTERVAL 4 DAY - INTERVAL 11 HOUR),'A few slips on inheritance. Re-read the section on constructors and super().',3,(NOW() - INTERVAL 4 DAY - INTERVAL 11 HOUR)),
(8,1,5,5,5,6,(NOW() - INTERVAL 1 DAY - INTERVAL 9 HOUR - INTERVAL 9 MINUTE),(NOW() - INTERVAL 1 DAY - INTERVAL 9 HOUR),NULL,NULL,NULL),
(9,1,6,4,4,6,(NOW() - INTERVAL 13 DAY - INTERVAL 16 HOUR - INTERVAL 8 MINUTE),(NOW() - INTERVAL 13 DAY - INTERVAL 16 HOUR),NULL,NULL,NULL),
(10,2,6,4,4,6,(NOW() - INTERVAL 10 DAY - INTERVAL 11 HOUR - INTERVAL 6 MINUTE),(NOW() - INTERVAL 10 DAY - INTERVAL 11 HOUR),'Good understanding of the basics. Practice generics wildcards a bit more.',2,(NOW() - INTERVAL 10 DAY - INTERVAL 11 HOUR)),
(11,3,6,4,4,6,(NOW() - INTERVAL 8 DAY - INTERVAL 15 HOUR - INTERVAL 4 MINUTE),(NOW() - INTERVAL 8 DAY - INTERVAL 15 HOUR),NULL,NULL,NULL),
(12,2,7,5,5,6,(NOW() - INTERVAL 7 DAY - INTERVAL 19 HOUR - INTERVAL 7 MINUTE),(NOW() - INTERVAL 7 DAY - INTERVAL 19 HOUR),NULL,NULL,NULL),
(13,3,7,5,5,6,(NOW() - INTERVAL 6 DAY - INTERVAL 11 HOUR - INTERVAL 11 MINUTE),(NOW() - INTERVAL 6 DAY - INTERVAL 11 HOUR),'Good understanding of the basics. Practice generics wildcards a bit more.',3,(NOW() - INTERVAL 6 DAY - INTERVAL 11 HOUR)),
(14,4,7,5,5,6,(NOW() - INTERVAL 5 DAY - INTERVAL 17 HOUR - INTERVAL 5 MINUTE),(NOW() - INTERVAL 5 DAY - INTERVAL 17 HOUR),NULL,NULL,NULL),
(15,4,7,2,2,6,(NOW() - INTERVAL 4 DAY - INTERVAL 18 HOUR - INTERVAL 6 MINUTE),(NOW() - INTERVAL 4 DAY - INTERVAL 18 HOUR),NULL,NULL,NULL),
(16,1,8,1,1,6,(NOW() - INTERVAL 12 DAY - INTERVAL 20 HOUR - INTERVAL 7 MINUTE),(NOW() - INTERVAL 12 DAY - INTERVAL 20 HOUR),'A few slips on inheritance. Re-read the section on constructors and super().',2,(NOW() - INTERVAL 12 DAY - INTERVAL 20 HOUR)),
(17,3,8,2,2,6,(NOW() - INTERVAL 6 DAY - INTERVAL 9 HOUR - INTERVAL 8 MINUTE),(NOW() - INTERVAL 6 DAY - INTERVAL 9 HOUR),NULL,NULL,NULL),
(18,1,8,2,2,6,(NOW() - INTERVAL 1 DAY - INTERVAL 10 HOUR - INTERVAL 5 MINUTE),(NOW() - INTERVAL 1 DAY - INTERVAL 10 HOUR),NULL,NULL,NULL);

INSERT INTO answers(attempt_id,question_id,selected_option,is_correct) VALUES
(1,1,'A',0),
(1,2,'C',1),
(1,3,'D',0),
(1,4,'D',0),
(1,5,'B',1),
(1,6,'B',1),
(2,1,'B',1),
(2,2,'C',1),
(2,3,NULL,0),
(2,4,'B',1),
(2,5,'B',1),
(2,6,'B',1),
(3,7,'B',1),
(3,8,'A',0),
(3,9,'A',0),
(3,10,'A',1),
(3,11,'A',1),
(3,12,'B',1),
(4,1,'B',1),
(4,2,'C',1),
(4,3,'C',1),
(4,4,'B',1),
(4,5,'C',0),
(4,6,'B',1),
(5,7,'B',1),
(5,8,'B',1),
(5,9,'D',1),
(5,10,'A',1),
(5,11,NULL,0),
(5,12,'B',1),
(6,13,'C',1),
(6,14,'C',1),
(6,15,'B',1),
(6,16,'B',1),
(6,17,'B',1),
(6,18,'B',1),
(7,19,'B',1),
(7,20,'C',1),
(7,21,'B',1),
(7,22,'B',1),
(7,23,'B',1),
(7,24,'B',1),
(8,1,'B',1),
(8,2,'C',1),
(8,3,'D',0),
(8,4,'B',1),
(8,5,'B',1),
(8,6,'B',1),
(9,1,'B',1),
(9,2,'C',1),
(9,3,'D',0),
(9,4,'C',0),
(9,5,'B',1),
(9,6,'B',1),
(10,7,'B',1),
(10,8,'B',1),
(10,9,'C',0),
(10,10,'A',1),
(10,11,'D',0),
(10,12,'B',1),
(11,13,'C',1),
(11,14,'C',1),
(11,15,NULL,0),
(11,16,'B',1),
(11,17,'D',0),
(11,18,'B',1),
(12,7,'B',1),
(12,8,'B',1),
(12,9,'C',0),
(12,10,'A',1),
(12,11,'A',1),
(12,12,'B',1),
(13,13,'C',1),
(13,14,'C',1),
(13,15,'B',1),
(13,16,NULL,0),
(13,17,'B',1),
(13,18,'B',1),
(14,19,'B',1),
(14,20,'C',1),
(14,21,'B',1),
(14,22,'D',0),
(14,23,'B',1),
(14,24,'B',1),
(15,19,'D',0),
(15,20,'D',0),
(15,21,'B',1),
(15,22,NULL,0),
(15,23,'C',0),
(15,24,'B',1),
(16,1,'D',0),
(16,2,'A',0),
(16,3,'D',0),
(16,4,'B',1),
(16,5,'D',0),
(16,6,'A',0),
(17,13,'D',0),
(17,14,'C',1),
(17,15,'D',0),
(17,16,'D',0),
(17,17,'A',0),
(17,18,'B',1),
(18,1,'A',0),
(18,2,'A',0),
(18,3,'C',1),
(18,4,'A',0),
(18,5,'B',1),
(18,6,NULL,0);

INSERT INTO messages(sender_id,receiver_id,message_text,is_read,created_at) VALUES
(4,2,'Hello sir, could you explain why finally runs even after a return statement?',1,NOW() - INTERVAL 3 DAY),
(2,4,'Hi Aarav! Yes - the JVM executes the finally block before the method actually returns. Try it with a print statement.',1,NOW() - INTERVAL 3 DAY + INTERVAL 20 MINUTE),
(4,2,'That makes sense, thank you!',1,NOW() - INTERVAL 3 DAY + INTERVAL 45 MINUTE),
(2,4,'Great job on the Java Fundamentals quiz. Try the OOP quiz next - it builds on it.',0,NOW() - INTERVAL 2 HOUR),
(5,3,'Ma''am, will there be a harder Collections quiz?',1,NOW() - INTERVAL 1 DAY),
(3,5,'Yes, one on streams and Comparators is coming next week.',0,NOW() - INTERVAL 5 HOUR);

INSERT INTO notifications(user_id,level,message,link,is_read,created_at) VALUES
(1,'WARNING','Mr. Sharma submitted "JDBC & Servlets Basics" for approval.','/admin/quizzes',0,NOW() - INTERVAL 20 HOUR),
(1,'INFO','Kabir Singh just registered as a participant.','/admin/users',0,NOW() - INTERVAL 2 DAY),
(1,'INFO','System started. Reminder scheduler is running.',NULL,1,NOW() - INTERVAL 5 DAY),
(2,'INFO','Aarav Mehta completed "Object-Oriented Programming in Java".','/creator/results',0,NOW() - INTERVAL 1 DAY),
(2,'WARNING','Your quiz "Strings & Arrays" was rejected. Open it to see why.','/creator/quizzes',0,NOW() - INTERVAL 3 DAY),
(4,'SUCCESS','Mr. Sharma reviewed your result for "Java Fundamentals".','/participant/reports',0,NOW() - INTERVAL 6 HOUR);

INSERT INTO reminders(participant_id,quiz_id,remind_at,note,notified) VALUES
(4,4,NOW() + INTERVAL 1 DAY,'Exceptions & Multithreading - revise first',0),
(4,3,NOW() + INTERVAL 3 DAY,'Collections practice',0),
(4,4,NOW() - INTERVAL 1 MINUTE,'Due now - the scheduler will turn this into a notification',0);

INSERT INTO system_settings(setting_key,setting_value) VALUES
('platform_name','QuizMania'),
('allow_registration','true'),
('max_attempts','3'),
('default_duration','15'),
('pass_percentage','40'),
('announcement','Welcome to QuizMania - test your knowledge and climb the leaderboard!');
